services:
  saving-account-backend:
    build:
      context: .
      dockerfile: saving/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - saving-account-network

  saving-account-frontend:
    build:
      context: .
      dockerfile: saving-account/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - saving-account-backend
    networks:
      - saving-account-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=saving_account_db
      - POSTGRES_USER=saving-account-user
      - POSTGRES_PASSWORD=saving-account-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - saving-account-network

networks:
  saving-account-network:
    driver: bridge

volumes:
  postgres-data:
