/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  cid: string;
  email: string;
  englishName: string;
  password: string;
  pin: string;
  thaiName: string;
}
